### ISSUE TITLE
Doesn't appear to work with name attributes with brackets

### ISSUE THREAD

**Issue by mseymour** [dkeeghan/jQuery-doWhen#1]
I've been trying to use doWhen with select elements that have brackets in their name (e,g. `user[selectOptions]`), but it doesn't seem to want to work.

**Comment by dkeeghan** [comment]
The ID selectors have been updated from using `$('#' + id)` to use `$('[id="' + id + '"]')` instead. This resolves the issue by allowing square brackets internally.
